### ISSUE TITLE
Error in is.finite(X) : default method not implemented for type 'list'

### ISSUE THREAD

**Issue by s-yadav21** [broadinstitute/cdsr_models#1]
When I am using the cdsr_model package to compute linear association for my dataset, I am getting this error: Error in is.finite(X) : default method not implemented for type 'list'

For my feature set I am using the gene expression data from Depmap portal. I made sure my feature matrix and response matrix have same number of rows.

`library(devtools)
devtools::install_github("broadinstitute/cdsr_models", force = TRUE)
cdsrmodels::lin_associations(A, y, W=NULL)`

**Comment by aboghossian** [comment]
Hi! Are you sure that your gene expression data is in matrix form (not a dataframe or tibble)? I will add this check to make the error more interpretable (or convert) but my guess is that is the issue

**Comment by s-yadav21** [comment]
> Hi! Are you sure that your gene expression data is in matrix form (not a dataframe or tibble)? I will add this check to make the error more interpretable (or convert) but my guess is that is the issue

Thank you for your prompt response, I had to convert the data into matrix.
